test:
    image: newser_server
    container_name: server_newser
    # restart: always
    volumes:
        - "/srv/logs/newser_server:/usr/src/app/logs"
    ports:
        - "5000:5000"
    environment:
        - SERVER_PORT=5000
        - RABBIT_USER=admin
        - RABBIT_PASSWORD=admin
        - RABBIT_HOST=10.19.19.4
        - RABBIT_PORT=5672
        - PG_USERNAME=postgres
        - PG_PASSWORD=12345678
        - PG_HOST=10.19.19.4
        - PG_PORT=35432
        - PG_DB=ias_db
        - QUERY_URL=http://10.19.19.4:1680/admin/give_search_query
        - DEFAULT_PAGES=1
        - SERVER_SOURCE=server
        - LOCAL_FILE_SOURCE=file
        - WEB_APP_SOURCE=web
        - PUPPETEER_QUEUE=puppeteer_bot
        - QUEUE_FILE=queries