test:
    image: newser_telegram
    container_name: telegram_newser
    # restart: always
    volumes:
        - "/srv/logs/newser_telegram:/usr/src/app/logs"
    ports:
        - "88:88"
    environment:
        - SERVER_PORT=5000
        - SERVER_HOST=10.13.7.65
        - TOKEN=1277676880:AAFOqL_vL43D2TelLOhvN2She7tl9558ph4
        - CHAT_ID=174055421